version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels: ["dependencies", "skip-changelog"]
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels: ["dependencies", "skip-changelog"]
    groups:
      dev-dependencies:
        patterns: ["pytest*", "ruff", "pyright", "pre-commit", "towncrier", "pyyaml", "scikit-build-core", "pybind11"]
