from __future__ import annotations

from typing import Protocol

class _NativeRow(Protocol):
    key: int
    value: int
    text: str

class _Database:
    def __init__(self, path: str) -> None: ...
    def begin(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def insert(self, key: int, value: int, text: str) -> None: ...
    def get(self, key: int) -> _NativeRow: ...
    def update(self, key: int, value: int | None, text: str | None) -> None: ...
    def delete(self, key: int) -> None: ...
    def size(self) -> int: ...
    def checkpoint(self) -> None: ...
    def close(self) -> None: ...
